-- supabase/neon/002_contractor_schema.sql
-- GENERATED by scripts/phase3-generate-ddl.sh — do not hand-edit; regenerate instead.
--
-- Contractor-owned tables for Work.WitUS's own database (Phase 3 of the split).
--
-- ⚠️ THREE THINGS TO REVIEW BEFORE RUNNING THIS ON NEON. They are Supabase-isms that do not exist
-- there, and this file reproduces them verbatim on purpose so the differences are visible rather
-- than silently dropped:
--
--   1. FOREIGN KEYS TO auth.users. Neon has no auth schema. Every `REFERENCES auth.users(id)`
--      must be re-pointed at Work.WitUS's own users table — this is the Route B identity work,
--      and it is the actual content of this migration.
--   2. RLS POLICIES referencing auth.uid(). That function does not exist on Neon. Either port the
--      policies to whatever Work.WitUS uses for row scoping, or drop RLS and enforce in the app.
--      Do not leave a policy referencing a missing function; it fails at query time, not at
--      creation.
--   3. gen_random_uuid() needs pgcrypto (or PG13+ built-in). Verify on the target.
--
-- Order below is dependency-ordered by hand where FKs require it (jobs before job children).

-- ─────────────────────────────────────────────────────────────
-- profiles
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profiles (
  id uuid NOT NULL,
  username text NOT NULL,
  display_name text,
  bio text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  subscription_status text DEFAULT 'free'::text NOT NULL,
  stripe_customer_id text,
  stripe_subscription_id text,
  subscription_expires_at timestamp with time zone,
  shirt_promo_code text,
  cancel_at_period_end boolean DEFAULT false,
  cancel_at timestamp with time zone,
  cancellation_feedback text,
  cancellation_comment text,
  role text DEFAULT 'member'::text NOT NULL,
  dashboard_home text DEFAULT '/dashboard/blog'::text,
  scan_auto_save_images boolean DEFAULT false,
  contractor_role text DEFAULT 'worker'::text,
  products text[] DEFAULT '{}'::text[],
  lister_company_name text,
  lister_union_local text,
  likes_public boolean DEFAULT false NOT NULL,
  show_done_counts boolean DEFAULT false NOT NULL,
  public_alias text,
  onboarding_completed boolean DEFAULT false,
  first_module_slug text,
  clock_format text DEFAULT '12h'::text NOT NULL,
  invite_limit integer,
  fiscal_year_start_month integer DEFAULT 1,
  fiscal_year_start_day integer DEFAULT 1,
  theme text DEFAULT 'light'::text NOT NULL,
  dashboard_home_centos text DEFAULT '/dashboard/blog'::text,
  selected_modules text[],
  lead_session_id text
);
ALTER TABLE profiles ADD CONSTRAINT profiles_public_alias_key UNIQUE (public_alias);
ALTER TABLE profiles ADD CONSTRAINT profiles_username_key UNIQUE (username);
ALTER TABLE profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE profiles ADD CONSTRAINT profiles_bio_check CHECK ((char_length(bio) <= 300));
ALTER TABLE profiles ADD CONSTRAINT profiles_clock_format_check CHECK ((clock_format = ANY (ARRAY['12h'::text, '24h'::text])));
ALTER TABLE profiles ADD CONSTRAINT profiles_contractor_role_check CHECK ((contractor_role = ANY (ARRAY['worker'::text, 'lister'::text, 'union_leader'::text])));
ALTER TABLE profiles ADD CONSTRAINT profiles_display_name_check CHECK ((char_length(display_name) <= 60));
ALTER TABLE profiles ADD CONSTRAINT profiles_fiscal_year_start_day_check CHECK (((fiscal_year_start_day >= 1) AND (fiscal_year_start_day <= 28)));
ALTER TABLE profiles ADD CONSTRAINT profiles_fiscal_year_start_month_check CHECK (((fiscal_year_start_month >= 1) AND (fiscal_year_start_month <= 12)));
ALTER TABLE profiles ADD CONSTRAINT profiles_role_check CHECK ((role = ANY (ARRAY['member'::text, 'teacher'::text, 'admin'::text])));
ALTER TABLE profiles ADD CONSTRAINT profiles_subscription_status_check CHECK ((subscription_status = ANY (ARRAY['free'::text, 'monthly'::text, 'annual'::text, 'lifetime'::text, 'starter'::text])));
ALTER TABLE profiles ADD CONSTRAINT profiles_theme_check CHECK ((theme = ANY (ARRAY['light'::text, 'dark'::text, 'system'::text])));
ALTER TABLE profiles ADD CONSTRAINT profiles_username_check CHECK ((username ~ '^[a-z0-9_-]{3,30}$'::text));
CREATE INDEX idx_profiles_stripe_customer_id ON public.profiles USING btree (stripe_customer_id);
CREATE INDEX idx_profiles_subscription_status ON public.profiles USING btree (subscription_status);
CREATE INDEX idx_profiles_username ON public.profiles USING btree (username);

-- ─────────────────────────────────────────────────────────────
-- user_brands
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_brands (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  dba_name text,
  ein text,
  address text,
  website text,
  color text DEFAULT '#6366f1'::text NOT NULL,
  description text,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE user_brands ADD CONSTRAINT user_brands_pkey PRIMARY KEY (id);
ALTER TABLE user_brands ADD CONSTRAINT user_brands_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX user_brands_user_id_idx ON public.user_brands USING btree (user_id);

-- ─────────────────────────────────────────────────────────────
-- financial_accounts
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS financial_accounts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  account_type text NOT NULL,
  institution_name text,
  last_four character(4),
  interest_rate numeric(5,2),
  credit_limit numeric(10,2),
  opening_balance numeric(10,2) DEFAULT 0 NOT NULL,
  monthly_fee numeric(10,2),
  due_date integer,
  statement_date integer,
  is_active boolean DEFAULT true NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  teller_enrollment_id uuid,
  teller_account_id text,
  last_synced_at timestamp with time zone,
  oldest_transaction_date date,
  dispute_window_days integer,
  default_return_days integer,
  promo_apr numeric(5,2),
  promo_apr_expires date,
  promo_description text,
  bt_apr numeric(5,2),
  bt_fee_percent numeric(5,2),
  bt_expires date,
  bt_description text,
  rewards_type text,
  rewards_rate text,
  annual_fee numeric(10,2)
);
ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_pkey PRIMARY KEY (id);
ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_teller_enrollment_id_fkey FOREIGN KEY (teller_enrollment_id) REFERENCES teller_enrollments(id) ON DELETE SET NULL;
ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_account_type_check CHECK ((account_type = ANY (ARRAY['checking'::text, 'savings'::text, 'credit_card'::text, 'loan'::text, 'cash'::text])));
ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_due_date_check CHECK (((due_date >= 1) AND (due_date <= 28)));
ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_statement_date_check CHECK (((statement_date >= 1) AND (statement_date <= 28)));
CREATE INDEX financial_accounts_user_id_idx ON public.financial_accounts USING btree (user_id);
CREATE INDEX idx_fa_teller_account ON public.financial_accounts USING btree (teller_account_id) WHERE (teller_account_id IS NOT NULL);

-- ─────────────────────────────────────────────────────────────
-- budget_categories
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS budget_categories (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  monthly_budget numeric(10,2),
  color text DEFAULT '#6366f1'::text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE budget_categories ADD CONSTRAINT budget_categories_pkey PRIMARY KEY (id);
ALTER TABLE budget_categories ADD CONSTRAINT budget_categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX idx_budget_categories_user ON public.budget_categories USING btree (user_id);

-- ─────────────────────────────────────────────────────────────
-- user_contacts
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_contacts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  contact_type text NOT NULL,
  default_category_id uuid,
  notes text,
  use_count integer DEFAULT 1 NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  email text,
  phone text,
  is_contractor boolean DEFAULT false,
  linked_user_id uuid,
  skills text[],
  availability_notes text,
  contact_subtype text,
  job_title text,
  company_name text,
  home_city text,
  home_state text,
  home_country text,
  last_worked_with date,
  total_jobs_together integer DEFAULT 0 NOT NULL,
  website text,
  paycheck_portal_url text,
  paycheck_portal_company_id text
);
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_user_id_name_contact_type_key UNIQUE (user_id, name, contact_type);
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_pkey PRIMARY KEY (id);
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_default_category_id_fkey FOREIGN KEY (default_category_id) REFERENCES budget_categories(id) ON DELETE SET NULL;
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_linked_user_id_fkey FOREIGN KEY (linked_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_contact_type_check CHECK ((contact_type = ANY (ARRAY['vendor'::text, 'customer'::text, 'location'::text])));
CREATE INDEX idx_contacts_contractor ON public.user_contacts USING btree (is_contractor) WHERE (is_contractor = true);
CREATE INDEX user_contacts_user_id_contact_type_idx ON public.user_contacts USING btree (user_id, contact_type);

-- ─────────────────────────────────────────────────────────────
-- financial_transactions
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS financial_transactions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  category_id uuid,
  amount numeric(10,2) NOT NULL,
  type text DEFAULT 'expense'::text NOT NULL,
  description text,
  vendor text,
  transaction_date date NOT NULL,
  source text DEFAULT 'manual'::text,
  tags text[],
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  account_id uuid,
  source_module text,
  source_module_id uuid,
  brand_id uuid,
  teller_transaction_id text,
  dispute_status text,
  dispute_date date,
  dispute_notes text,
  return_deadline date,
  return_policy_days integer,
  return_status text,
  job_id uuid
);
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_pkey PRIMARY KEY (id);
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES financial_accounts(id) ON DELETE SET NULL;
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES user_brands(id) ON DELETE SET NULL;
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES budget_categories(id) ON DELETE SET NULL;
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_job_id_fkey FOREIGN KEY (job_id) REFERENCES contractor_jobs(id) ON DELETE SET NULL;
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_dispute_status_check CHECK (((dispute_status IS NULL) OR (dispute_status = ANY (ARRAY['flagged'::text, 'submitted'::text, 'resolved'::text, 'denied'::text]))));
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_return_status_check CHECK (((return_status IS NULL) OR (return_status = ANY (ARRAY['eligible'::text, 'expired'::text, 'returned'::text]))));
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_source_check CHECK ((source = ANY (ARRAY['manual'::text, 'csv_import'::text, 'stripe'::text, 'fuel_log'::text, 'vehicle_maintenance'::text, 'trip'::text, 'transfer'::text, 'interest'::text, 'recurring'::text, 'scan'::text, 'bank_sync'::text, 'job'::text, 'schedule'::text])));
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_source_module_check CHECK (((source_module IS NULL) OR (source_module = ANY (ARRAY['fuel_log'::text, 'vehicle_maintenance'::text, 'trip'::text, 'scan'::text, 'job'::text, 'schedule'::text]))));
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_type_check CHECK ((type = ANY (ARRAY['expense'::text, 'income'::text])));
CREATE INDEX financial_transactions_account_id_idx ON public.financial_transactions USING btree (account_id);
CREATE INDEX financial_transactions_brand_id_idx ON public.financial_transactions USING btree (brand_id);
CREATE INDEX financial_transactions_source_module_source_module_id_idx ON public.financial_transactions USING btree (source_module, source_module_id);
CREATE INDEX idx_financial_transactions_category ON public.financial_transactions USING btree (category_id);
CREATE INDEX idx_financial_transactions_date ON public.financial_transactions USING btree (transaction_date);
CREATE INDEX idx_financial_transactions_type ON public.financial_transactions USING btree (type);
CREATE INDEX idx_financial_transactions_user ON public.financial_transactions USING btree (user_id);
CREATE INDEX idx_ft_job ON public.financial_transactions USING btree (job_id);
CREATE UNIQUE INDEX idx_ft_teller_txn ON public.financial_transactions USING btree (teller_transaction_id) WHERE (teller_transaction_id IS NOT NULL);

-- RLS policies on the moved tables, for reference. See warning 2 in the header.
-- profiles :: Profiles are publicly readable :: true
-- profiles :: Users can manage their own profile :: (auth.uid() = id)
-- user_brands :: users manage own brands :: (auth.uid() = user_id)
-- financial_accounts :: users manage own financial accounts :: (auth.uid() = user_id)
-- budget_categories :: Users can CRUD their budget categories :: (auth.uid() = user_id)
-- user_contacts :: users manage own contacts :: (auth.uid() = user_id)
-- financial_transactions :: Users can CRUD their financial transactions :: (auth.uid() = user_id)
