-- supabase/neon/004_neon_ready.sql
-- GENERATED by scripts/phase3-neonize.mjs from 002 + 003. Do not hand-edit; regenerate.
--
-- Run this against Work.WitUS's Neon database. It is the Supabase DDL with three deliberate
-- changes, described in the script header and summarised here:
--
--   IDENTITY  27 foreign keys to auth.users now reference profiles(id) instead.
--             profiles is the identity table on Neon. Its id IS the original auth user UUID, so
--             every existing foreign key value stays valid and nothing needs remapping.
--             profiles' own FK to auth.users is dropped; it is now a plain primary key.
--
--   ORDERING  Tables, then constraints, then indexes — and within constraints, primary and
--             unique keys before foreign keys, which need them to exist. The source files group
--             per table, which cannot be run top to bottom. Both orderings were found by
--             dry-running this file, not by reading it.
--
--   DANGLING  1 foreign key(s) dropped because their target is not created here.
--             Listed at the bottom of this file. The COLUMNS are kept as soft references.
--
--   RLS       Dropped, not ported. Work.WitUS uses the service-role key in 247 routes (which
--             bypasses RLS) and scopes every query in application code. The policies below are
--             preserved as comments so this is reversible.
--
-- EXTENSIONS: required, and found by dry-running this file against a scratch database rather
-- than by reading it. union_document_chunks.embedding is vector(768) — the union RAG store — so
-- pgvector must exist before the tables are created. Neon supports it; it still has to be enabled.

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid(); built in on PG13+, harmless if so

BEGIN;

-- ── 1. Tables ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profiles (
  id uuid NOT NULL,
  username text NOT NULL,
  display_name text,
  bio text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  subscription_status text DEFAULT 'free'::text NOT NULL,
  stripe_customer_id text,
  stripe_subscription_id text,
  subscription_expires_at timestamp with time zone,
  shirt_promo_code text,
  cancel_at_period_end boolean DEFAULT false,
  cancel_at timestamp with time zone,
  cancellation_feedback text,
  cancellation_comment text,
  role text DEFAULT 'member'::text NOT NULL,
  dashboard_home text DEFAULT '/dashboard/blog'::text,
  scan_auto_save_images boolean DEFAULT false,
  contractor_role text DEFAULT 'worker'::text,
  products text[] DEFAULT '{}'::text[],
  lister_company_name text,
  lister_union_local text,
  likes_public boolean DEFAULT false NOT NULL,
  show_done_counts boolean DEFAULT false NOT NULL,
  public_alias text,
  onboarding_completed boolean DEFAULT false,
  first_module_slug text,
  clock_format text DEFAULT '12h'::text NOT NULL,
  invite_limit integer,
  fiscal_year_start_month integer DEFAULT 1,
  fiscal_year_start_day integer DEFAULT 1,
  theme text DEFAULT 'light'::text NOT NULL,
  dashboard_home_centos text DEFAULT '/dashboard/blog'::text,
  selected_modules text[],
  lead_session_id text
);

CREATE TABLE IF NOT EXISTS user_brands (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  dba_name text,
  ein text,
  address text,
  website text,
  color text DEFAULT '#6366f1'::text NOT NULL,
  description text,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS financial_accounts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  account_type text NOT NULL,
  institution_name text,
  last_four character(4),
  interest_rate numeric(5,2),
  credit_limit numeric(10,2),
  opening_balance numeric(10,2) DEFAULT 0 NOT NULL,
  monthly_fee numeric(10,2),
  due_date integer,
  statement_date integer,
  is_active boolean DEFAULT true NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  teller_enrollment_id uuid,
  teller_account_id text,
  last_synced_at timestamp with time zone,
  oldest_transaction_date date,
  dispute_window_days integer,
  default_return_days integer,
  promo_apr numeric(5,2),
  promo_apr_expires date,
  promo_description text,
  bt_apr numeric(5,2),
  bt_fee_percent numeric(5,2),
  bt_expires date,
  bt_description text,
  rewards_type text,
  rewards_rate text,
  annual_fee numeric(10,2)
);

CREATE TABLE IF NOT EXISTS budget_categories (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  monthly_budget numeric(10,2),
  color text DEFAULT '#6366f1'::text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS user_contacts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  contact_type text NOT NULL,
  default_category_id uuid,
  notes text,
  use_count integer DEFAULT 1 NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  email text,
  phone text,
  is_contractor boolean DEFAULT false,
  linked_user_id uuid,
  skills text[],
  availability_notes text,
  contact_subtype text,
  job_title text,
  company_name text,
  home_city text,
  home_state text,
  home_country text,
  last_worked_with date,
  total_jobs_together integer DEFAULT 0 NOT NULL,
  website text,
  paycheck_portal_url text,
  paycheck_portal_company_id text
);

CREATE TABLE IF NOT EXISTS financial_transactions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  category_id uuid,
  amount numeric(10,2) NOT NULL,
  type text DEFAULT 'expense'::text NOT NULL,
  description text,
  vendor text,
  transaction_date date NOT NULL,
  source text DEFAULT 'manual'::text,
  tags text[],
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  account_id uuid,
  source_module text,
  source_module_id uuid,
  brand_id uuid,
  teller_transaction_id text,
  dispute_status text,
  dispute_date date,
  dispute_notes text,
  return_deadline date,
  return_policy_days integer,
  return_status text,
  job_id uuid
);

CREATE TABLE IF NOT EXISTS contractor_jobs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  job_number text NOT NULL,
  client_id uuid,
  client_name text NOT NULL,
  event_name text,
  location_id uuid,
  location_name text,
  poc_contact_id uuid,
  poc_name text,
  poc_phone text,
  crew_coordinator_id uuid,
  crew_coordinator_name text,
  crew_coordinator_phone text,
  status text DEFAULT 'assigned'::text NOT NULL,
  start_date date,
  end_date date,
  is_multi_day boolean DEFAULT false NOT NULL,
  scheduled_dates jsonb DEFAULT '[]'::jsonb NOT NULL,
  pay_rate numeric(10,2),
  ot_rate numeric(10,2),
  dt_rate numeric(10,2),
  rate_type text DEFAULT 'hourly'::text NOT NULL,
  distance_from_home_miles numeric(8,2),
  benefits_eligible boolean DEFAULT false NOT NULL,
  travel_benefits jsonb DEFAULT '{}'::jsonb NOT NULL,
  union_local text,
  department text,
  brand_id uuid,
  est_pay_date date,
  is_public boolean DEFAULT false NOT NULL,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  rate_card_id uuid,
  share_contacts boolean DEFAULT false NOT NULL,
  distance_from_home_km numeric(8,2),
  benefit_deductions jsonb DEFAULT '[]'::jsonb NOT NULL,
  lister_id uuid,
  is_lister_job boolean DEFAULT false,
  event_id uuid
);

CREATE TABLE IF NOT EXISTS contractor_job_assignments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  assigned_by uuid NOT NULL,
  assigned_to uuid NOT NULL,
  status text DEFAULT 'offered'::text NOT NULL,
  message text,
  response_note text,
  assigned_at timestamp with time zone DEFAULT now(),
  responded_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS contractor_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  client_id uuid,
  client_name text,
  location_id uuid,
  location_name text,
  poc_contact_id uuid,
  poc_name text,
  poc_phone text,
  crew_coordinator_id uuid,
  crew_coordinator_name text,
  crew_coordinator_phone text,
  start_date date,
  end_date date,
  union_local text,
  department text,
  brand_id uuid,
  pay_rate numeric(10,2),
  ot_rate numeric(10,2),
  dt_rate numeric(10,2),
  rate_type text DEFAULT 'hourly'::text,
  benefits_eligible boolean DEFAULT false NOT NULL,
  travel_benefits jsonb DEFAULT '{}'::jsonb NOT NULL,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS contractor_rate_cards (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  union_local text,
  department text,
  rate_type text DEFAULT 'hourly'::text NOT NULL,
  st_rate numeric(10,2),
  ot_rate numeric(10,2),
  dt_rate numeric(10,2),
  benefits jsonb DEFAULT '[]'::jsonb NOT NULL,
  travel_benefits jsonb DEFAULT '{}'::jsonb NOT NULL,
  notes text,
  use_count integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS job_time_entries (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  user_id uuid NOT NULL,
  work_date date NOT NULL,
  time_in timestamp with time zone,
  time_out timestamp with time zone,
  adjusted_in timestamp with time zone,
  adjusted_out timestamp with time zone,
  break_minutes integer DEFAULT 0 NOT NULL,
  total_hours numeric(6,2),
  st_hours numeric(6,2),
  ot_hours numeric(6,2),
  dt_hours numeric(6,2),
  meal_provided boolean DEFAULT false NOT NULL,
  invoice_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  benefit_deductions jsonb DEFAULT '[]'::jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS job_notes (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  user_id uuid NOT NULL,
  content text DEFAULT ''::text NOT NULL,
  is_public boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS job_documents (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  url text,
  doc_type text DEFAULT 'other'::text NOT NULL,
  is_shared boolean DEFAULT false NOT NULL,
  file_size integer,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  doc_category text,
  title text,
  description text,
  metadata jsonb
);

CREATE TABLE IF NOT EXISTS job_replacement_requests (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_id uuid NOT NULL,
  poster_id uuid NOT NULL,
  requester_id uuid NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  message text,
  poster_note text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS invoices (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  direction text NOT NULL,
  status text DEFAULT 'draft'::text NOT NULL,
  contact_name text NOT NULL,
  contact_id uuid,
  subtotal numeric(10,2) DEFAULT 0 NOT NULL,
  tax_amount numeric(10,2) DEFAULT 0 NOT NULL,
  total numeric(10,2) DEFAULT 0 NOT NULL,
  amount_paid numeric(10,2) DEFAULT 0 NOT NULL,
  invoice_date date DEFAULT CURRENT_DATE NOT NULL,
  due_date date,
  paid_date date,
  invoice_number text,
  account_id uuid,
  brand_id uuid,
  category_id uuid,
  transaction_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  invoice_number_prefix text,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  job_id uuid,
  paycheck_id uuid
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  invoice_id uuid NOT NULL,
  description text NOT NULL,
  quantity numeric(10,2) DEFAULT 1 NOT NULL,
  unit_price numeric(10,2) DEFAULT 0 NOT NULL,
  amount numeric(10,2) DEFAULT 0 NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  item_type text DEFAULT 'line_item'::text NOT NULL
);

CREATE TABLE IF NOT EXISTS invoice_templates (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  direction text DEFAULT 'receivable'::text NOT NULL,
  contact_name text,
  contact_id uuid,
  subtotal numeric(10,2) DEFAULT 0,
  tax_amount numeric(10,2) DEFAULT 0,
  total numeric(10,2) DEFAULT 0,
  account_id uuid,
  brand_id uuid,
  category_id uuid,
  notes text,
  use_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invoice_number_prefix text,
  custom_fields jsonb DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS invoice_template_items (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  template_id uuid NOT NULL,
  description text DEFAULT ''::text NOT NULL,
  quantity numeric(10,2) DEFAULT 1,
  unit_price numeric(10,2) DEFAULT 0,
  amount numeric(10,2) DEFAULT 0,
  sort_order integer DEFAULT 0,
  item_type text DEFAULT 'line_item'::text NOT NULL
);

CREATE TABLE IF NOT EXISTS paychecks (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  job_id uuid,
  paycheck_number text,
  pay_period_start date NOT NULL,
  pay_period_end date NOT NULL,
  pay_date date NOT NULL,
  gross_amount numeric(10,2) DEFAULT 0 NOT NULL,
  benefits_total numeric(10,2) DEFAULT 0 NOT NULL,
  taxes_total numeric(10,2) DEFAULT 0 NOT NULL,
  other_deductions jsonb DEFAULT '[]'::jsonb NOT NULL,
  other_deductions_total numeric(10,2) DEFAULT 0 NOT NULL,
  net_amount numeric(10,2) DEFAULT 0 NOT NULL,
  expected_gross numeric(10,2),
  variance_amount numeric(10,2),
  variance_notes text,
  status text DEFAULT 'draft'::text NOT NULL,
  is_reconciled boolean DEFAULT false NOT NULL,
  reconciled_at timestamp with time zone,
  brand_id uuid,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS paycheck_invoices (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  paycheck_id uuid NOT NULL,
  invoice_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS paycheck_taxes (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  paycheck_id uuid NOT NULL,
  tax_type text NOT NULL,
  label text NOT NULL,
  expected_amount numeric(10,2),
  actual_amount numeric(10,2) DEFAULT 0 NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  notes text
);

CREATE TABLE IF NOT EXISTS paycheck_deposits (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  paycheck_id uuid NOT NULL,
  account_id uuid NOT NULL,
  amount numeric(10,2) NOT NULL,
  percentage numeric(5,2),
  deposit_type text DEFAULT 'direct_deposit'::text NOT NULL,
  transaction_id uuid,
  label text,
  sort_order integer DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS union_memberships (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  union_name text NOT NULL,
  local_number text NOT NULL,
  member_id text,
  status text DEFAULT 'active'::text NOT NULL,
  join_date date,
  expiration_date date,
  dues_amount numeric(10,2),
  dues_frequency text DEFAULT 'quarterly'::text,
  next_dues_date date,
  auto_pay boolean DEFAULT false,
  initiation_fee numeric(10,2),
  initiation_paid boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS union_dues_payments (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  membership_id uuid NOT NULL,
  user_id uuid NOT NULL,
  amount numeric(10,2) NOT NULL,
  payment_date date NOT NULL,
  period_start date,
  period_end date,
  payment_method text,
  confirmation_number text,
  transaction_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS union_documents (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  union_local text,
  doc_url text,
  doc_type text NOT NULL,
  is_shared boolean DEFAULT false,
  status text DEFAULT 'pending'::text,
  error_msg text,
  page_count integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS union_document_chunks (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  document_id uuid NOT NULL,
  chunk_text text NOT NULL,
  chunk_index integer NOT NULL,
  embedding vector(768),
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS union_rag_submissions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  file_url text NOT NULL,
  file_name text NOT NULL,
  union_local text,
  doc_type text NOT NULL,
  description text,
  coverage_dates text,
  status text DEFAULT 'pending'::text NOT NULL,
  admin_notes text,
  document_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  replaces_document_id uuid
);

CREATE TABLE IF NOT EXISTS contact_phones (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  contact_id uuid NOT NULL,
  phone text NOT NULL,
  label text DEFAULT 'mobile'::text,
  is_primary boolean DEFAULT false NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS contact_emails (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  contact_id uuid NOT NULL,
  email text NOT NULL,
  label text DEFAULT 'work'::text,
  is_primary boolean DEFAULT false NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS contact_tags (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  contact_id uuid NOT NULL,
  tag_type text NOT NULL,
  value text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS contact_job_roles (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  contact_id uuid NOT NULL,
  job_id uuid NOT NULL,
  event_id uuid,
  role text NOT NULL,
  role_label text,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS contact_shares (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  contact_id uuid NOT NULL,
  shared_by uuid NOT NULL,
  shared_with uuid NOT NULL,
  message text,
  status text DEFAULT 'pending'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  visible_fields jsonb DEFAULT '["name", "company_name", "job_title", "email", "phone", "notes", "addresses", "tags", "website", "paycheck_portal"]'::jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS contact_addresses (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  contact_id uuid NOT NULL,
  label text DEFAULT 'home'::text NOT NULL,
  street text,
  city text,
  state text,
  postal_code text,
  country text,
  is_primary boolean DEFAULT false NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS contact_locations (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  contact_id uuid NOT NULL,
  label text NOT NULL,
  address text,
  lat numeric(10,7),
  lng numeric(10,7),
  is_default boolean DEFAULT false NOT NULL,
  notes text,
  sort_order integer DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  schematics_url text,
  knowledge_base jsonb DEFAULT '{}'::jsonb
);

-- ── 2. Constraints ───────────────────────────────────────────────────────────
ALTER TABLE profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE user_brands ADD CONSTRAINT user_brands_pkey PRIMARY KEY (id);
ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_pkey PRIMARY KEY (id);
ALTER TABLE budget_categories ADD CONSTRAINT budget_categories_pkey PRIMARY KEY (id);
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_pkey PRIMARY KEY (id);
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_pkey PRIMARY KEY (id);
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_pkey PRIMARY KEY (id);
ALTER TABLE contractor_job_assignments ADD CONSTRAINT contractor_job_assignments_pkey PRIMARY KEY (id);
ALTER TABLE contractor_events ADD CONSTRAINT contractor_events_pkey PRIMARY KEY (id);
ALTER TABLE contractor_rate_cards ADD CONSTRAINT contractor_rate_cards_pkey PRIMARY KEY (id);
ALTER TABLE job_time_entries ADD CONSTRAINT job_time_entries_pkey PRIMARY KEY (id);
ALTER TABLE job_notes ADD CONSTRAINT job_notes_pkey PRIMARY KEY (id);
ALTER TABLE job_documents ADD CONSTRAINT job_documents_pkey PRIMARY KEY (id);
ALTER TABLE job_replacement_requests ADD CONSTRAINT job_replacement_requests_pkey PRIMARY KEY (id);
ALTER TABLE invoices ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);
ALTER TABLE invoice_items ADD CONSTRAINT invoice_items_pkey PRIMARY KEY (id);
ALTER TABLE invoice_templates ADD CONSTRAINT invoice_templates_pkey PRIMARY KEY (id);
ALTER TABLE invoice_template_items ADD CONSTRAINT invoice_template_items_pkey PRIMARY KEY (id);
ALTER TABLE paychecks ADD CONSTRAINT paychecks_pkey PRIMARY KEY (id);
ALTER TABLE paycheck_invoices ADD CONSTRAINT paycheck_invoices_pkey PRIMARY KEY (id);
ALTER TABLE paycheck_taxes ADD CONSTRAINT paycheck_taxes_pkey PRIMARY KEY (id);
ALTER TABLE paycheck_deposits ADD CONSTRAINT paycheck_deposits_pkey PRIMARY KEY (id);
ALTER TABLE union_memberships ADD CONSTRAINT union_memberships_pkey PRIMARY KEY (id);
ALTER TABLE union_dues_payments ADD CONSTRAINT union_dues_payments_pkey PRIMARY KEY (id);
ALTER TABLE union_documents ADD CONSTRAINT union_documents_pkey PRIMARY KEY (id);
ALTER TABLE union_document_chunks ADD CONSTRAINT union_document_chunks_pkey PRIMARY KEY (id);
ALTER TABLE union_rag_submissions ADD CONSTRAINT union_rag_submissions_pkey PRIMARY KEY (id);
ALTER TABLE contact_phones ADD CONSTRAINT contact_phones_pkey PRIMARY KEY (id);
ALTER TABLE contact_emails ADD CONSTRAINT contact_emails_pkey PRIMARY KEY (id);
ALTER TABLE contact_tags ADD CONSTRAINT contact_tags_pkey PRIMARY KEY (id);
ALTER TABLE contact_job_roles ADD CONSTRAINT contact_job_roles_pkey PRIMARY KEY (id);
ALTER TABLE contact_shares ADD CONSTRAINT contact_shares_pkey PRIMARY KEY (id);
ALTER TABLE contact_addresses ADD CONSTRAINT contact_addresses_pkey PRIMARY KEY (id);
ALTER TABLE contact_locations ADD CONSTRAINT contact_locations_pkey PRIMARY KEY (id);
ALTER TABLE profiles ADD CONSTRAINT profiles_public_alias_key UNIQUE (public_alias);
ALTER TABLE profiles ADD CONSTRAINT profiles_username_key UNIQUE (username);
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_user_id_name_contact_type_key UNIQUE (user_id, name, contact_type);
ALTER TABLE contractor_job_assignments ADD CONSTRAINT contractor_job_assignments_job_id_assigned_to_key UNIQUE (job_id, assigned_to);
ALTER TABLE job_replacement_requests ADD CONSTRAINT job_replacement_requests_job_id_requester_id_key UNIQUE (job_id, requester_id);
ALTER TABLE paycheck_invoices ADD CONSTRAINT paycheck_invoices_paycheck_id_invoice_id_key UNIQUE (paycheck_id, invoice_id);
ALTER TABLE union_memberships ADD CONSTRAINT union_memberships_user_id_union_name_local_number_key UNIQUE (user_id, union_name, local_number);
ALTER TABLE contact_tags ADD CONSTRAINT contact_tags_contact_id_tag_type_value_key UNIQUE (contact_id, tag_type, value);
ALTER TABLE contact_job_roles ADD CONSTRAINT contact_job_roles_contact_id_job_id_role_key UNIQUE (contact_id, job_id, role);
ALTER TABLE contact_shares ADD CONSTRAINT contact_shares_contact_id_shared_with_key UNIQUE (contact_id, shared_with);
ALTER TABLE profiles ADD CONSTRAINT profiles_bio_check CHECK ((char_length(bio) <= 300));
ALTER TABLE profiles ADD CONSTRAINT profiles_clock_format_check CHECK ((clock_format = ANY (ARRAY['12h'::text, '24h'::text])));
ALTER TABLE profiles ADD CONSTRAINT profiles_contractor_role_check CHECK ((contractor_role = ANY (ARRAY['worker'::text, 'lister'::text, 'union_leader'::text])));
ALTER TABLE profiles ADD CONSTRAINT profiles_display_name_check CHECK ((char_length(display_name) <= 60));
ALTER TABLE profiles ADD CONSTRAINT profiles_fiscal_year_start_day_check CHECK (((fiscal_year_start_day >= 1) AND (fiscal_year_start_day <= 28)));
ALTER TABLE profiles ADD CONSTRAINT profiles_fiscal_year_start_month_check CHECK (((fiscal_year_start_month >= 1) AND (fiscal_year_start_month <= 12)));
ALTER TABLE profiles ADD CONSTRAINT profiles_role_check CHECK ((role = ANY (ARRAY['member'::text, 'teacher'::text, 'admin'::text])));
ALTER TABLE profiles ADD CONSTRAINT profiles_subscription_status_check CHECK ((subscription_status = ANY (ARRAY['free'::text, 'monthly'::text, 'annual'::text, 'lifetime'::text, 'starter'::text])));
ALTER TABLE profiles ADD CONSTRAINT profiles_theme_check CHECK ((theme = ANY (ARRAY['light'::text, 'dark'::text, 'system'::text])));
ALTER TABLE profiles ADD CONSTRAINT profiles_username_check CHECK ((username ~ '^[a-z0-9_-]{3,30}$'::text));
ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_account_type_check CHECK ((account_type = ANY (ARRAY['checking'::text, 'savings'::text, 'credit_card'::text, 'loan'::text, 'cash'::text])));
ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_due_date_check CHECK (((due_date >= 1) AND (due_date <= 28)));
ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_statement_date_check CHECK (((statement_date >= 1) AND (statement_date <= 28)));
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_contact_type_check CHECK ((contact_type = ANY (ARRAY['vendor'::text, 'customer'::text, 'location'::text])));
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_dispute_status_check CHECK (((dispute_status IS NULL) OR (dispute_status = ANY (ARRAY['flagged'::text, 'submitted'::text, 'resolved'::text, 'denied'::text]))));
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_return_status_check CHECK (((return_status IS NULL) OR (return_status = ANY (ARRAY['eligible'::text, 'expired'::text, 'returned'::text]))));
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_source_check CHECK ((source = ANY (ARRAY['manual'::text, 'csv_import'::text, 'stripe'::text, 'fuel_log'::text, 'vehicle_maintenance'::text, 'trip'::text, 'transfer'::text, 'interest'::text, 'recurring'::text, 'scan'::text, 'bank_sync'::text, 'job'::text, 'schedule'::text])));
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_source_module_check CHECK (((source_module IS NULL) OR (source_module = ANY (ARRAY['fuel_log'::text, 'vehicle_maintenance'::text, 'trip'::text, 'scan'::text, 'job'::text, 'schedule'::text]))));
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_type_check CHECK ((type = ANY (ARRAY['expense'::text, 'income'::text])));
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_rate_type_check CHECK ((rate_type = ANY (ARRAY['hourly'::text, 'daily'::text, 'flat'::text])));
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_status_check CHECK ((status = ANY (ARRAY['assigned'::text, 'confirmed'::text, 'in_progress'::text, 'completed'::text, 'invoiced'::text, 'paid'::text, 'cancelled'::text])));
ALTER TABLE contractor_job_assignments ADD CONSTRAINT contractor_job_assignments_status_check CHECK ((status = ANY (ARRAY['offered'::text, 'accepted'::text, 'declined'::text, 'removed'::text])));
ALTER TABLE contractor_events ADD CONSTRAINT contractor_events_rate_type_check CHECK ((rate_type = ANY (ARRAY['hourly'::text, 'daily'::text, 'flat'::text])));
ALTER TABLE contractor_rate_cards ADD CONSTRAINT contractor_rate_cards_rate_type_check CHECK ((rate_type = ANY (ARRAY['hourly'::text, 'daily'::text, 'flat'::text])));
ALTER TABLE job_documents ADD CONSTRAINT job_documents_doc_type_check CHECK ((doc_type = ANY (ARRAY['call_sheet'::text, 'crew_list'::text, 'w9'::text, 'certificate'::text, 'contract'::text, 'receipt'::text, 'schematic'::text, 'map'::text, 'other'::text])));
ALTER TABLE job_replacement_requests ADD CONSTRAINT job_replacement_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'withdrawn'::text])));
ALTER TABLE invoices ADD CONSTRAINT invoices_direction_check CHECK ((direction = ANY (ARRAY['receivable'::text, 'payable'::text])));
ALTER TABLE invoices ADD CONSTRAINT invoices_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'sent'::text, 'paid'::text, 'overdue'::text, 'cancelled'::text])));
ALTER TABLE invoice_items ADD CONSTRAINT invoice_items_item_type_check CHECK ((item_type = ANY (ARRAY['line_item'::text, 'benefit'::text])));
ALTER TABLE invoice_templates ADD CONSTRAINT invoice_templates_direction_check CHECK ((direction = ANY (ARRAY['receivable'::text, 'payable'::text])));
ALTER TABLE invoice_template_items ADD CONSTRAINT invoice_template_items_item_type_check CHECK ((item_type = ANY (ARRAY['line_item'::text, 'benefit'::text])));
ALTER TABLE paychecks ADD CONSTRAINT paychecks_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'pending'::text, 'reconciled'::text, 'disputed'::text])));
ALTER TABLE paycheck_taxes ADD CONSTRAINT paycheck_taxes_tax_type_check CHECK ((tax_type = ANY (ARRAY['federal'::text, 'state'::text, 'local'::text, 'fica_ss'::text, 'fica_medicare'::text, 'state_disability'::text, 'state_unemployment'::text, 'local_other'::text, 'other'::text])));
ALTER TABLE paycheck_deposits ADD CONSTRAINT paycheck_deposits_deposit_type_check CHECK ((deposit_type = ANY (ARRAY['direct_deposit'::text, 'check'::text, 'cash'::text, 'other'::text])));
ALTER TABLE union_memberships ADD CONSTRAINT union_memberships_dues_frequency_check CHECK ((dues_frequency = ANY (ARRAY['monthly'::text, 'quarterly'::text, 'semi_annual'::text, 'annual'::text])));
ALTER TABLE union_memberships ADD CONSTRAINT union_memberships_status_check CHECK ((status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text, 'retired'::text, 'honorary'::text])));
ALTER TABLE union_documents ADD CONSTRAINT union_documents_doc_type_check CHECK ((doc_type = ANY (ARRAY['contract'::text, 'bylaws'::text, 'rate_sheet'::text, 'rules'::text, 'other'::text])));
ALTER TABLE union_documents ADD CONSTRAINT union_documents_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'ready'::text, 'error'::text])));
ALTER TABLE union_rag_submissions ADD CONSTRAINT union_rag_submissions_doc_type_check CHECK ((doc_type = ANY (ARRAY['contract'::text, 'bylaws'::text, 'rate_sheet'::text, 'rules'::text, 'other'::text])));
ALTER TABLE union_rag_submissions ADD CONSTRAINT union_rag_submissions_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'processing'::text, 'live'::text])));
ALTER TABLE contact_tags ADD CONSTRAINT contact_tags_tag_type_check CHECK ((tag_type = ANY (ARRAY['company'::text, 'role'::text, 'skill'::text, 'group'::text, 'custom'::text])));
ALTER TABLE contact_job_roles ADD CONSTRAINT contact_job_roles_role_check CHECK ((role = ANY (ARRAY['poc'::text, 'crew_coordinator'::text, 'tech_lead'::text, 'producer'::text, 'eic'::text, 'a1'::text, 'a2'::text, 'v1'::text, 'v2'::text, 'graphics'::text, 'replay'::text, 'utility'::text, 'other'::text])));
ALTER TABLE contact_shares ADD CONSTRAINT contact_shares_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text])));
ALTER TABLE user_brands ADD CONSTRAINT user_brands_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE budget_categories ADD CONSTRAINT budget_categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_default_category_id_fkey FOREIGN KEY (default_category_id) REFERENCES budget_categories(id) ON DELETE SET NULL;
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_linked_user_id_fkey FOREIGN KEY (linked_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE user_contacts ADD CONSTRAINT user_contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES financial_accounts(id) ON DELETE SET NULL;
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES user_brands(id) ON DELETE SET NULL;
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES budget_categories(id) ON DELETE SET NULL;
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_job_id_fkey FOREIGN KEY (job_id) REFERENCES contractor_jobs(id) ON DELETE SET NULL;
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES user_brands(id) ON DELETE SET NULL;
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_client_id_fkey FOREIGN KEY (client_id) REFERENCES user_contacts(id) ON DELETE SET NULL;
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_crew_coordinator_id_fkey FOREIGN KEY (crew_coordinator_id) REFERENCES user_contacts(id) ON DELETE SET NULL;
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_event_id_fkey FOREIGN KEY (event_id) REFERENCES contractor_events(id) ON DELETE SET NULL;
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_lister_id_fkey FOREIGN KEY (lister_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_location_id_fkey FOREIGN KEY (location_id) REFERENCES contact_locations(id) ON DELETE SET NULL;
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_poc_contact_id_fkey FOREIGN KEY (poc_contact_id) REFERENCES user_contacts(id) ON DELETE SET NULL;
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_rate_card_id_fkey FOREIGN KEY (rate_card_id) REFERENCES contractor_rate_cards(id) ON DELETE SET NULL;
ALTER TABLE contractor_jobs ADD CONSTRAINT contractor_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE contractor_job_assignments ADD CONSTRAINT contractor_job_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE contractor_job_assignments ADD CONSTRAINT contractor_job_assignments_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE contractor_job_assignments ADD CONSTRAINT contractor_job_assignments_job_id_fkey FOREIGN KEY (job_id) REFERENCES contractor_jobs(id) ON DELETE CASCADE;
ALTER TABLE contractor_events ADD CONSTRAINT contractor_events_client_id_fkey FOREIGN KEY (client_id) REFERENCES user_contacts(id) ON DELETE SET NULL;
ALTER TABLE contractor_events ADD CONSTRAINT contractor_events_crew_coordinator_id_fkey FOREIGN KEY (crew_coordinator_id) REFERENCES user_contacts(id) ON DELETE SET NULL;
ALTER TABLE contractor_events ADD CONSTRAINT contractor_events_location_id_fkey FOREIGN KEY (location_id) REFERENCES contact_locations(id) ON DELETE SET NULL;
ALTER TABLE contractor_events ADD CONSTRAINT contractor_events_poc_contact_id_fkey FOREIGN KEY (poc_contact_id) REFERENCES user_contacts(id) ON DELETE SET NULL;
ALTER TABLE contractor_events ADD CONSTRAINT contractor_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE contractor_rate_cards ADD CONSTRAINT contractor_rate_cards_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE job_time_entries ADD CONSTRAINT job_time_entries_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL;
ALTER TABLE job_time_entries ADD CONSTRAINT job_time_entries_job_id_fkey FOREIGN KEY (job_id) REFERENCES contractor_jobs(id) ON DELETE CASCADE;
ALTER TABLE job_time_entries ADD CONSTRAINT job_time_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE job_notes ADD CONSTRAINT job_notes_job_id_fkey FOREIGN KEY (job_id) REFERENCES contractor_jobs(id) ON DELETE CASCADE;
ALTER TABLE job_notes ADD CONSTRAINT job_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE job_documents ADD CONSTRAINT job_documents_job_id_fkey FOREIGN KEY (job_id) REFERENCES contractor_jobs(id) ON DELETE CASCADE;
ALTER TABLE job_documents ADD CONSTRAINT job_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE job_replacement_requests ADD CONSTRAINT job_replacement_requests_job_id_fkey FOREIGN KEY (job_id) REFERENCES contractor_jobs(id) ON DELETE CASCADE;
ALTER TABLE job_replacement_requests ADD CONSTRAINT job_replacement_requests_poster_id_fkey FOREIGN KEY (poster_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE job_replacement_requests ADD CONSTRAINT job_replacement_requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE invoices ADD CONSTRAINT invoices_account_id_fkey FOREIGN KEY (account_id) REFERENCES financial_accounts(id) ON DELETE SET NULL;
ALTER TABLE invoices ADD CONSTRAINT invoices_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES user_brands(id) ON DELETE SET NULL;
ALTER TABLE invoices ADD CONSTRAINT invoices_category_id_fkey FOREIGN KEY (category_id) REFERENCES budget_categories(id) ON DELETE SET NULL;
ALTER TABLE invoices ADD CONSTRAINT invoices_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES user_contacts(id) ON DELETE SET NULL;
ALTER TABLE invoices ADD CONSTRAINT invoices_job_id_fkey FOREIGN KEY (job_id) REFERENCES contractor_jobs(id) ON DELETE SET NULL;
ALTER TABLE invoices ADD CONSTRAINT invoices_paycheck_id_fkey FOREIGN KEY (paycheck_id) REFERENCES paychecks(id) ON DELETE SET NULL;
ALTER TABLE invoices ADD CONSTRAINT invoices_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES financial_transactions(id) ON DELETE SET NULL;
ALTER TABLE invoices ADD CONSTRAINT invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE invoice_items ADD CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE;
ALTER TABLE invoice_templates ADD CONSTRAINT invoice_templates_account_id_fkey FOREIGN KEY (account_id) REFERENCES financial_accounts(id) ON DELETE SET NULL;
ALTER TABLE invoice_templates ADD CONSTRAINT invoice_templates_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES user_brands(id) ON DELETE SET NULL;
ALTER TABLE invoice_templates ADD CONSTRAINT invoice_templates_category_id_fkey FOREIGN KEY (category_id) REFERENCES budget_categories(id) ON DELETE SET NULL;
ALTER TABLE invoice_templates ADD CONSTRAINT invoice_templates_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES user_contacts(id) ON DELETE SET NULL;
ALTER TABLE invoice_templates ADD CONSTRAINT invoice_templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE invoice_template_items ADD CONSTRAINT invoice_template_items_template_id_fkey FOREIGN KEY (template_id) REFERENCES invoice_templates(id) ON DELETE CASCADE;
ALTER TABLE paychecks ADD CONSTRAINT paychecks_job_id_fkey FOREIGN KEY (job_id) REFERENCES contractor_jobs(id) ON DELETE SET NULL;
ALTER TABLE paychecks ADD CONSTRAINT paychecks_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE paycheck_invoices ADD CONSTRAINT paycheck_invoices_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE;
ALTER TABLE paycheck_invoices ADD CONSTRAINT paycheck_invoices_paycheck_id_fkey FOREIGN KEY (paycheck_id) REFERENCES paychecks(id) ON DELETE CASCADE;
ALTER TABLE paycheck_taxes ADD CONSTRAINT paycheck_taxes_paycheck_id_fkey FOREIGN KEY (paycheck_id) REFERENCES paychecks(id) ON DELETE CASCADE;
ALTER TABLE paycheck_deposits ADD CONSTRAINT paycheck_deposits_account_id_fkey FOREIGN KEY (account_id) REFERENCES financial_accounts(id) ON DELETE CASCADE;
ALTER TABLE paycheck_deposits ADD CONSTRAINT paycheck_deposits_paycheck_id_fkey FOREIGN KEY (paycheck_id) REFERENCES paychecks(id) ON DELETE CASCADE;
ALTER TABLE paycheck_deposits ADD CONSTRAINT paycheck_deposits_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES financial_transactions(id) ON DELETE SET NULL;
ALTER TABLE union_memberships ADD CONSTRAINT union_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE union_dues_payments ADD CONSTRAINT union_dues_payments_membership_id_fkey FOREIGN KEY (membership_id) REFERENCES union_memberships(id) ON DELETE CASCADE;
ALTER TABLE union_dues_payments ADD CONSTRAINT union_dues_payments_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES financial_transactions(id) ON DELETE SET NULL;
ALTER TABLE union_dues_payments ADD CONSTRAINT union_dues_payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE union_documents ADD CONSTRAINT union_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE union_document_chunks ADD CONSTRAINT union_document_chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES union_documents(id) ON DELETE CASCADE;
ALTER TABLE union_rag_submissions ADD CONSTRAINT union_rag_submissions_document_id_fkey FOREIGN KEY (document_id) REFERENCES union_documents(id) ON DELETE SET NULL;
ALTER TABLE union_rag_submissions ADD CONSTRAINT union_rag_submissions_replaces_document_id_fkey FOREIGN KEY (replaces_document_id) REFERENCES union_documents(id) ON DELETE SET NULL;
ALTER TABLE union_rag_submissions ADD CONSTRAINT union_rag_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE contact_phones ADD CONSTRAINT contact_phones_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES user_contacts(id) ON DELETE CASCADE;
ALTER TABLE contact_emails ADD CONSTRAINT contact_emails_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES user_contacts(id) ON DELETE CASCADE;
ALTER TABLE contact_tags ADD CONSTRAINT contact_tags_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES user_contacts(id) ON DELETE CASCADE;
ALTER TABLE contact_job_roles ADD CONSTRAINT contact_job_roles_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES user_contacts(id) ON DELETE CASCADE;
ALTER TABLE contact_job_roles ADD CONSTRAINT contact_job_roles_event_id_fkey FOREIGN KEY (event_id) REFERENCES contractor_events(id) ON DELETE SET NULL;
ALTER TABLE contact_job_roles ADD CONSTRAINT contact_job_roles_job_id_fkey FOREIGN KEY (job_id) REFERENCES contractor_jobs(id) ON DELETE CASCADE;
ALTER TABLE contact_shares ADD CONSTRAINT contact_shares_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES user_contacts(id) ON DELETE CASCADE;
ALTER TABLE contact_shares ADD CONSTRAINT contact_shares_shared_by_fkey FOREIGN KEY (shared_by) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE contact_shares ADD CONSTRAINT contact_shares_shared_with_fkey FOREIGN KEY (shared_with) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE contact_addresses ADD CONSTRAINT contact_addresses_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES user_contacts(id) ON DELETE CASCADE;
ALTER TABLE contact_locations ADD CONSTRAINT contact_locations_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES user_contacts(id) ON DELETE CASCADE;

-- ── 3. Indexes ───────────────────────────────────────────────────────────────
CREATE INDEX idx_profiles_stripe_customer_id ON public.profiles USING btree (stripe_customer_id);
CREATE INDEX idx_profiles_subscription_status ON public.profiles USING btree (subscription_status);
CREATE INDEX idx_profiles_username ON public.profiles USING btree (username);
CREATE INDEX user_brands_user_id_idx ON public.user_brands USING btree (user_id);
CREATE INDEX financial_accounts_user_id_idx ON public.financial_accounts USING btree (user_id);
CREATE INDEX idx_fa_teller_account ON public.financial_accounts USING btree (teller_account_id) WHERE (teller_account_id IS NOT NULL);
CREATE INDEX idx_budget_categories_user ON public.budget_categories USING btree (user_id);
CREATE INDEX idx_contacts_contractor ON public.user_contacts USING btree (is_contractor) WHERE (is_contractor = true);
CREATE INDEX user_contacts_user_id_contact_type_idx ON public.user_contacts USING btree (user_id, contact_type);
CREATE INDEX financial_transactions_account_id_idx ON public.financial_transactions USING btree (account_id);
CREATE INDEX financial_transactions_brand_id_idx ON public.financial_transactions USING btree (brand_id);
CREATE INDEX financial_transactions_source_module_source_module_id_idx ON public.financial_transactions USING btree (source_module, source_module_id);
CREATE INDEX idx_financial_transactions_category ON public.financial_transactions USING btree (category_id);
CREATE INDEX idx_financial_transactions_date ON public.financial_transactions USING btree (transaction_date);
CREATE INDEX idx_financial_transactions_type ON public.financial_transactions USING btree (type);
CREATE INDEX idx_financial_transactions_user ON public.financial_transactions USING btree (user_id);
CREATE INDEX idx_ft_job ON public.financial_transactions USING btree (job_id);
CREATE UNIQUE INDEX idx_ft_teller_txn ON public.financial_transactions USING btree (teller_transaction_id) WHERE (teller_transaction_id IS NOT NULL);
CREATE INDEX idx_contractor_jobs_client ON public.contractor_jobs USING btree (client_id);
CREATE INDEX idx_contractor_jobs_dates ON public.contractor_jobs USING btree (user_id, start_date DESC);
CREATE INDEX idx_contractor_jobs_event ON public.contractor_jobs USING btree (event_id) WHERE (event_id IS NOT NULL);
CREATE UNIQUE INDEX idx_contractor_jobs_number ON public.contractor_jobs USING btree (user_id, job_number);
CREATE INDEX idx_contractor_jobs_status ON public.contractor_jobs USING btree (user_id, status);
CREATE INDEX idx_contractor_jobs_user ON public.contractor_jobs USING btree (user_id);
CREATE INDEX idx_assignments_assigned_by ON public.contractor_job_assignments USING btree (assigned_by);
CREATE INDEX idx_assignments_assigned_to ON public.contractor_job_assignments USING btree (assigned_to);
CREATE INDEX idx_assignments_job ON public.contractor_job_assignments USING btree (job_id);
CREATE INDEX idx_contractor_events_user ON public.contractor_events USING btree (user_id, start_date DESC);
CREATE INDEX idx_rate_cards_user ON public.contractor_rate_cards USING btree (user_id);
CREATE INDEX idx_job_time_entries_date ON public.job_time_entries USING btree (user_id, work_date DESC);
CREATE INDEX idx_job_time_entries_job ON public.job_time_entries USING btree (job_id);
CREATE UNIQUE INDEX idx_job_time_entries_unique ON public.job_time_entries USING btree (job_id, user_id, work_date);
CREATE INDEX idx_job_notes_job ON public.job_notes USING btree (job_id);
CREATE INDEX idx_job_notes_public ON public.job_notes USING btree (job_id) WHERE (is_public = true);
CREATE INDEX idx_job_notes_user ON public.job_notes USING btree (user_id, created_at DESC);
CREATE INDEX idx_job_documents_category ON public.job_documents USING btree (job_id, doc_category);
CREATE INDEX idx_job_documents_job ON public.job_documents USING btree (job_id);
CREATE INDEX idx_replacement_req_job ON public.job_replacement_requests USING btree (job_id);
CREATE INDEX idx_replacement_req_poster ON public.job_replacement_requests USING btree (poster_id, status);
CREATE INDEX idx_replacement_req_requester ON public.job_replacement_requests USING btree (requester_id, status);
CREATE INDEX idx_invoices_job ON public.invoices USING btree (job_id);
CREATE INDEX idx_invoices_paycheck ON public.invoices USING btree (paycheck_id);
CREATE INDEX invoices_user_id_direction_idx ON public.invoices USING btree (user_id, direction);
CREATE INDEX invoices_user_id_due_date_idx ON public.invoices USING btree (user_id, due_date);
CREATE INDEX invoices_user_id_status_idx ON public.invoices USING btree (user_id, status);
CREATE INDEX invoice_items_invoice_id_idx ON public.invoice_items USING btree (invoice_id);
CREATE INDEX idx_paychecks_date ON public.paychecks USING btree (user_id, pay_date DESC);
CREATE INDEX idx_paychecks_job ON public.paychecks USING btree (job_id);
CREATE INDEX idx_paychecks_user ON public.paychecks USING btree (user_id);
CREATE INDEX idx_paycheck_invoices_invoice ON public.paycheck_invoices USING btree (invoice_id);
CREATE INDEX idx_paycheck_invoices_paycheck ON public.paycheck_invoices USING btree (paycheck_id);
CREATE INDEX idx_paycheck_taxes_paycheck ON public.paycheck_taxes USING btree (paycheck_id);
CREATE INDEX idx_paycheck_deposits_account ON public.paycheck_deposits USING btree (account_id);
CREATE INDEX idx_paycheck_deposits_paycheck ON public.paycheck_deposits USING btree (paycheck_id);
CREATE INDEX idx_union_memberships_user ON public.union_memberships USING btree (user_id);
CREATE INDEX idx_union_dues_membership ON public.union_dues_payments USING btree (membership_id);
CREATE INDEX idx_union_dues_user ON public.union_dues_payments USING btree (user_id);
CREATE INDEX idx_union_documents_shared ON public.union_documents USING btree (is_shared) WHERE (is_shared = true);
CREATE INDEX idx_union_documents_user ON public.union_documents USING btree (user_id);
CREATE INDEX idx_union_chunks_document ON public.union_document_chunks USING btree (document_id);
CREATE INDEX idx_union_chunks_embedding ON public.union_document_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists='50');
CREATE INDEX idx_rag_submissions_status ON public.union_rag_submissions USING btree (status);
CREATE INDEX idx_rag_submissions_user ON public.union_rag_submissions USING btree (user_id);
CREATE INDEX idx_contact_phones_contact ON public.contact_phones USING btree (contact_id);
CREATE INDEX idx_contact_emails_contact ON public.contact_emails USING btree (contact_id);
CREATE INDEX idx_contact_tags_contact ON public.contact_tags USING btree (contact_id);
CREATE INDEX idx_contact_tags_type_value ON public.contact_tags USING btree (tag_type, value);
CREATE INDEX idx_contact_job_roles_contact ON public.contact_job_roles USING btree (contact_id);
CREATE INDEX idx_contact_job_roles_job ON public.contact_job_roles USING btree (job_id);
CREATE INDEX idx_contact_shares_shared_by ON public.contact_shares USING btree (shared_by);
CREATE INDEX idx_contact_shares_shared_with ON public.contact_shares USING btree (shared_with, status);
CREATE INDEX idx_contact_addresses_contact ON public.contact_addresses USING btree (contact_id);
CREATE INDEX idx_contact_locations_contact ON public.contact_locations USING btree (contact_id);

COMMIT;

-- ── RLS policies as they exist on Supabase, for reference only ───────────────
-- Not created here. See the RLS note in the header before reinstating any of them.
-- profiles :: Profiles are publicly readable :: true
-- profiles :: Users can manage their own profile :: (auth.uid() = id)
-- user_brands :: users manage own brands :: (auth.uid() = user_id)
-- financial_accounts :: users manage own financial accounts :: (auth.uid() = user_id)
-- budget_categories :: Users can CRUD their budget categories :: (auth.uid() = user_id)
-- user_contacts :: users manage own contacts :: (auth.uid() = user_id)
-- financial_transactions :: Users can CRUD their financial transactions :: (auth.uid() = user_id)
-- contractor_jobs :: contractor_jobs_owner :: (user_id = auth.uid())
-- contractor_jobs :: contractor_jobs_public_read :: (is_public = true)
-- contractor_events :: contractor_events_owner :: (user_id = auth.uid())
-- contractor_rate_cards :: rate_cards_owner :: (user_id = auth.uid())
-- job_time_entries :: job_time_entries_owner :: (user_id = auth.uid())
-- job_notes :: job_notes_owner :: (user_id = auth.uid())
-- job_notes :: job_notes_public_assigned :: ((is_public = true) AND (EXISTS ( SELECT 1
-- job_notes :: job_notes_public_job_owner :: ((is_public = true) AND (EXISTS ( SELECT 1
-- job_notes :: job_notes_public_lister :: ((is_public = true) AND (EXISTS ( SELECT 1
-- job_documents :: job_documents_owner :: (user_id = auth.uid())
-- job_documents :: job_documents_shared_read :: (is_shared = true)
-- job_replacement_requests :: replacement_req_poster :: (poster_id = auth.uid())
-- job_replacement_requests :: replacement_req_requester :: (requester_id = auth.uid())
-- invoices :: invoices_owner :: (user_id = auth.uid())
-- invoice_items :: invoice_items_owner :: (invoice_id IN ( SELECT invoices.id
-- invoice_templates :: invoice_templates_owner :: (user_id = auth.uid())
-- invoice_template_items :: invoice_template_items_owner :: (template_id IN ( SELECT invoice_templates.id
-- paychecks :: paychecks_owner :: (user_id = auth.uid())
-- paycheck_invoices :: paycheck_invoices_owner :: (EXISTS ( SELECT 1
-- paycheck_taxes :: paycheck_taxes_owner :: (EXISTS ( SELECT 1
-- paycheck_deposits :: paycheck_deposits_owner :: (EXISTS ( SELECT 1
-- union_memberships :: union_memberships_owner :: (user_id = auth.uid())
-- union_dues_payments :: union_dues_payments_owner :: (user_id = auth.uid())
-- union_documents :: union_documents_owner :: (user_id = auth.uid())
-- union_documents :: union_documents_shared_read :: ((is_shared = true) AND (status = 'ready'::text))
-- union_document_chunks :: union_chunks_owner :: (EXISTS ( SELECT 1
-- union_document_chunks :: union_chunks_shared_read :: (EXISTS ( SELECT 1
-- union_rag_submissions :: rag_submissions_owner :: (user_id = auth.uid())
-- contact_phones :: contact_phones_owner :: (EXISTS ( SELECT 1
-- contact_emails :: contact_emails_owner :: (EXISTS ( SELECT 1
-- contact_tags :: contact_tags_owner :: (EXISTS ( SELECT 1
-- contact_job_roles :: contact_job_roles_owner :: (EXISTS ( SELECT 1
-- contact_shares :: contact_shares_recipient :: (shared_with = auth.uid())
-- contact_shares :: contact_shares_recipient_update :: (shared_with = auth.uid())
-- contact_shares :: contact_shares_sender :: (shared_by = auth.uid())
-- contact_addresses :: contact_addresses_owner :: (EXISTS ( SELECT 1
-- contact_locations :: contact_locations_owner :: (contact_id IN ( SELECT user_contacts.id

-- ── Foreign keys DROPPED because their target stays in CentOS ──────────────────
-- The columns are kept, so the values survive as soft references. Re-adding any of these
-- means deciding to copy its target table too.
--   target teller_enrollments:
--   ALTER TABLE financial_accounts ADD CONSTRAINT financial_accounts_teller_enrollment_id_fkey FOREIGN KEY (teller_enrollment_id) REFERENCES teller_enrollments(id) ON DELETE SET NULL;
