#!/usr/bin/env bash
# scripts/phase3-generate-ddl.sh
# Emit CREATE TABLE DDL for the contractor-owned tables, for the Neon side of the database split.
#
# WHY NOT pg_dump: the local client is 14 and the server is 17, and pg_dump refuses across major
# versions. Homebrew cannot install postgresql@17 on macOS 13 (unsupported, no bottle, source
# build aborts). psql has no such restriction, so this asks the SERVER to emit its own definitions
# via pg_get_constraintdef() and pg_get_indexdef() — the DDL is generated by Postgres, not
# transcribed by hand.
#
# Usage:
#   ./scripts/phase3-generate-ddl.sh "$SUPABASE_POSTGRES_URL" > supabase/neon/002_contractor_schema.sql
set -euo pipefail

URL="${1:?usage: phase3-generate-ddl.sh <postgres-url>}"

TABLES=(
  contractor_jobs contractor_job_assignments contractor_events contractor_rate_cards
  job_time_entries job_notes job_documents job_replacement_requests
  invoices invoice_items invoice_templates invoice_template_items
  paychecks paycheck_invoices paycheck_taxes paycheck_deposits
  union_memberships union_dues_payments union_documents union_document_chunks
  union_rag_submissions
  contact_phones contact_emails contact_tags contact_job_roles contact_shares
  contact_addresses contact_locations
)

cat <<'HDR'
-- supabase/neon/002_contractor_schema.sql
-- GENERATED by scripts/phase3-generate-ddl.sh — do not hand-edit; regenerate instead.
--
-- Contractor-owned tables for Work.WitUS's own database (Phase 3 of the split).
--
-- ⚠️ THREE THINGS TO REVIEW BEFORE RUNNING THIS ON NEON. They are Supabase-isms that do not exist
-- there, and this file reproduces them verbatim on purpose so the differences are visible rather
-- than silently dropped:
--
--   1. FOREIGN KEYS TO auth.users. Neon has no auth schema. Every `REFERENCES auth.users(id)`
--      must be re-pointed at Work.WitUS's own users table — this is the Route B identity work,
--      and it is the actual content of this migration.
--   2. RLS POLICIES referencing auth.uid(). That function does not exist on Neon. Either port the
--      policies to whatever Work.WitUS uses for row scoping, or drop RLS and enforce in the app.
--      Do not leave a policy referencing a missing function; it fails at query time, not at
--      creation.
--   3. gen_random_uuid() needs pgcrypto (or PG13+ built-in). Verify on the target.
--
-- Order below is dependency-ordered by hand where FKs require it (jobs before job children).
HDR

for t in "${TABLES[@]}"; do
  echo ""
  echo "-- ─────────────────────────────────────────────────────────────"
  echo "-- $t"
  echo "-- ─────────────────────────────────────────────────────────────"

  # Columns, in ordinal order. format_type() gives the exact declared type.
  psql "$URL" -tA -F $'\t' -v ON_ERROR_STOP=1 -c "
    SELECT 'CREATE TABLE IF NOT EXISTS ' || '$t' || ' (' || E'\n' ||
      string_agg(
        '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
        || COALESCE(' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid), '')
        || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
        ',' || E'\n' ORDER BY a.attnum)
      || E'\n);'
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    WHERE a.attrelid = '$t'::regclass AND a.attnum > 0 AND NOT a.attisdropped;
  "

  # Constraints: PK, UNIQUE, CHECK, FK — emitted by the server itself.
  psql "$URL" -tA -v ON_ERROR_STOP=1 -c "
    SELECT string_agg(
      'ALTER TABLE ' || '$t' || ' ADD CONSTRAINT ' || quote_ident(conname)
      || ' ' || pg_get_constraintdef(oid) || ';', E'\n' ORDER BY contype DESC, conname)
    FROM pg_constraint WHERE conrelid = '$t'::regclass;
  "

  # Indexes, excluding those Postgres creates for the constraints above.
  psql "$URL" -tA -v ON_ERROR_STOP=1 -c "
    SELECT string_agg(indexdef || ';', E'\n' ORDER BY indexname)
    FROM pg_indexes
    WHERE schemaname = 'public' AND tablename = '$t'
      AND indexname NOT IN (
        SELECT conname FROM pg_constraint WHERE conrelid = '$t'::regclass
      );
  "
done

echo ""
echo "-- RLS policies on the moved tables, for reference. See warning 2 in the header."
for t in "${TABLES[@]}"; do
  psql "$URL" -tA -v ON_ERROR_STOP=1 -c "
    SELECT string_agg(
      '-- ' || '$t' || ' :: ' || policyname || ' :: ' ||
      COALESCE(qual, '(no using)') , E'\n')
    FROM pg_policies WHERE schemaname='public' AND tablename = '$t';
  "
done
