#!/usr/bin/env node
// scripts/phase3-neonize.mjs
// Turn the server-generated Supabase DDL into something Neon can actually run.
//
// Reads supabase/neon/002_contractor_schema.sql and 003_copied_tables.sql (raw output from
// phase3-generate-ddl.sh, deliberately left un-edited so the diff is inspectable) and writes
// 004_neon_ready.sql.
//
// THREE TRANSFORMS, each of which is a decision, not a formatting change:
//
// 1. IDENTITY — `REFERENCES auth.users(id)` becomes `REFERENCES profiles(id)`.
//    This is Route B. Neon has no auth schema, so something else has to be the identity table,
//    and profiles is the natural choice: profiles.id IS the auth user's UUID
//    (023_profiles.sql: `id UUID PRIMARY KEY REFERENCES auth.users(id)`), so every existing
//    foreign key VALUE stays valid and no id remapping is needed anywhere. profiles' own FK to
//    auth.users is dropped; it becomes a plain primary key.
//
// 2. ORDERING — all CREATE TABLEs, then all constraints, then all indexes.
//    The generated files group each table with its own constraints, which fails the moment a
//    foreign key points at a table defined further down. Separating the phases removes the
//    ordering problem entirely rather than trying to topologically sort 34 tables.
//
// 3. RLS — dropped, not ported, and the header says why.
//    Work.WitUS queries with the service-role key in 247 routes, which BYPASSES RLS, and scopes
//    every query in application code (`.eq('user_id', user.id)`). So these policies are not what
//    enforces access today. Porting `auth.uid()` to a `current_setting()` shim would add a
//    mechanism nothing currently depends on. The policy list is preserved as comments so the
//    decision is reversible and visible.
//
// Usage: node scripts/phase3-neonize.mjs

import { readFileSync, writeFileSync } from 'node:fs';

const read = (p) => readFileSync(p, 'utf8');
const raw = [
  read('supabase/neon/003_copied_tables.sql'),   // identity + reference tables first
  read('supabase/neon/002_contractor_schema.sql'),
].join('\n');

const creates = [];
const constraints = [];
const indexes = [];
const policyNotes = [];

// CREATE TABLE blocks run until a line that is exactly ');'
const lines = raw.split('\n');
for (let i = 0; i < lines.length; i++) {
  const l = lines[i];
  if (l.startsWith('CREATE TABLE')) {
    const block = [l];
    while (i + 1 < lines.length && block[block.length - 1] !== ');') block.push(lines[++i]);
    creates.push(block.join('\n'));
  } else if (l.startsWith('ALTER TABLE') && l.includes('ADD CONSTRAINT')) {
    constraints.push(l);
  } else if (l.startsWith('CREATE INDEX') || l.startsWith('CREATE UNIQUE INDEX')) {
    indexes.push(l);
  } else if (l.startsWith('-- ') && l.includes(' :: ')) {
    policyNotes.push(l);
  }
}

// Transform 1: identity.
const rewritten = constraints
  // profiles' own link to auth.users has no target on Neon; profiles IS the identity table now.
  .filter((c) => !(c.startsWith('ALTER TABLE profiles') && c.includes('REFERENCES auth.users')))
  .map((c) => c.replace(/REFERENCES auth\.users\(/g, 'REFERENCES profiles('));

const authRefsBefore = constraints.filter((c) => c.includes('auth.users')).length;
const authRefsAfter = rewritten.filter((c) => c.includes('auth.users')).length;

// Transform 4: drop foreign keys whose TARGET is not being created here.
// Found by dry-running against a scratch database, not by reading: financial_accounts has an FK
// to teller_enrollments, CentOS's Teller bank-linking table. That one should NOT be copied — it
// holds bank connection tokens, and duplicating those into a second database is a security
// decision nobody asked for. Work.WitUS does not do bank linking at all.
// The column is kept as a soft reference; only the constraint goes.
const createdTables = new Set(
  creates.map((c) => c.match(/^CREATE TABLE IF NOT EXISTS ([a-z_]+)/)?.[1]).filter(Boolean),
);
const dangling = [];
const finalConstraints = rewritten.filter((c) => {
  const target = c.match(/REFERENCES ([a-z_]+)\(/)?.[1];
  if (target && !createdTables.has(target)) { dangling.push({ c, target }); return false; }
  return true;
});

// Dedupe: the two source files can both mention a shared table.
const uniq = (a) => [...new Set(a)];

// Within the constraints phase, order matters again: a FOREIGN KEY needs its target's PRIMARY KEY
// or UNIQUE to exist first ("there is no unique constraint matching given keys"). Found by
// dry-run. Sort keys before references, checks last.
const rank = (c) =>
  /PRIMARY KEY/.test(c) ? 0 : /UNIQUE/.test(c) ? 1 : /FOREIGN KEY/.test(c) ? 3 : 2;
const ordered = (a) => uniq(a).slice().sort((x, y) => rank(x) - rank(y));

const out = `-- supabase/neon/004_neon_ready.sql
-- GENERATED by scripts/phase3-neonize.mjs from 002 + 003. Do not hand-edit; regenerate.
--
-- Run this against Work.WitUS's Neon database. It is the Supabase DDL with three deliberate
-- changes, described in the script header and summarised here:
--
--   IDENTITY  ${authRefsBefore} foreign keys to auth.users now reference profiles(id) instead.
--             profiles is the identity table on Neon. Its id IS the original auth user UUID, so
--             every existing foreign key value stays valid and nothing needs remapping.
--             profiles' own FK to auth.users is dropped; it is now a plain primary key.
--
--   ORDERING  Tables, then constraints, then indexes — and within constraints, primary and
--             unique keys before foreign keys, which need them to exist. The source files group
--             per table, which cannot be run top to bottom. Both orderings were found by
--             dry-running this file, not by reading it.
--
--   DANGLING  ${dangling.length} foreign key(s) dropped because their target is not created here.
--             Listed at the bottom of this file. The COLUMNS are kept as soft references.
--
--   RLS       Dropped, not ported. Work.WitUS uses the service-role key in 247 routes (which
--             bypasses RLS) and scopes every query in application code. The policies below are
--             preserved as comments so this is reversible.
--
-- EXTENSIONS: required, and found by dry-running this file against a scratch database rather
-- than by reading it. union_document_chunks.embedding is vector(768) — the union RAG store — so
-- pgvector must exist before the tables are created. Neon supports it; it still has to be enabled.

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid(); built in on PG13+, harmless if so

BEGIN;

-- ── 1. Tables ────────────────────────────────────────────────────────────────
${uniq(creates).join('\n\n')}

-- ── 2. Constraints ───────────────────────────────────────────────────────────
${ordered(finalConstraints).join('\n')}

-- ── 3. Indexes ───────────────────────────────────────────────────────────────
${uniq(indexes).join('\n')}

COMMIT;

-- ── RLS policies as they exist on Supabase, for reference only ───────────────
-- Not created here. See the RLS note in the header before reinstating any of them.
${uniq(policyNotes).join('\n')}

-- ── Foreign keys DROPPED because their target stays in CentOS ──────────────────
-- The columns are kept, so the values survive as soft references. Re-adding any of these
-- means deciding to copy its target table too.
${dangling.map((d) => `--   target ${d.target}:\n--   ${d.c}`).join('\n')}
`;

writeFileSync('supabase/neon/004_neon_ready.sql', out);

console.log(`tables      ${uniq(creates).length}`);
console.log(`constraints ${uniq(finalConstraints).length}`);
console.log(`dropped FKs ${dangling.length} (target not in the set)`);
for (const d of dangling) console.log(`  -> ${d.target}`);
console.log(`indexes     ${uniq(indexes).length}`);
console.log(`policies    ${uniq(policyNotes).length} (documented, not created)`);
console.log(`auth.users references: ${authRefsBefore} -> ${authRefsAfter}`);
if (authRefsAfter > 0) {
  console.error('\nERROR: auth.users references remain. Neon has no auth schema; fix before running.');
  process.exit(1);
}
console.log('\nwrote supabase/neon/004_neon_ready.sql');
