// app/api/admin/content-status/route.ts
// Admin: returns last-modified dates for key content sources to detect staleness.
// Reads from a build-time manifest (generated by scripts/generate-content-manifest.mjs)
// because Vercel serverless functions don't have access to the full repo filesystem.

import { NextRequest, NextResponse } from 'next/server';
import { createServerClient, type CookieOptions } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { readFile } from 'fs/promises';
import { join } from 'path';

async function getAdminUser() {
  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get: (name: string) => cookieStore.get(name)?.value,
        set: (name: string, value: string, options: CookieOptions) => { try { cookieStore.set({ name, value, ...options }); } catch {} },
        remove: (name: string, options: CookieOptions) => { try { cookieStore.set({ name, value: '', ...options }); } catch {} },
      },
    },
  );
  const { data: { user } } = await supabase.auth.getUser();
  return user;
}

interface ManifestSource {
  key: string;
  label: string;
  description: string;
  path: string;
  modifiedAt: string | null;
  exists: boolean;
}

interface Manifest {
  generatedAt: string;
  sources: ManifestSource[];
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export async function GET(_request: NextRequest) {
  const user = await getAdminUser();
  if (!user || user.email !== process.env.ADMIN_EMAIL) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  const STALE_DAYS = 30;
  const now = Date.now();

  let manifest: Manifest;
  try {
    const manifestPath = join(process.cwd(), 'lib', 'generated', 'content-manifest.json');
    const raw = await readFile(manifestPath, 'utf-8');
    manifest = JSON.parse(raw);
  } catch {
    return NextResponse.json({
      sources: [],
      staleCount: 0,
      staleDays: STALE_DAYS,
      error: 'Content manifest not found. Run `node scripts/generate-content-manifest.mjs` or redeploy.',
    });
  }

  const results = manifest.sources.map((source) => {
    if (!source.exists || !source.modifiedAt) {
      return { ...source, daysSinceUpdate: null, stale: true };
    }
    const modifiedMs = new Date(source.modifiedAt).getTime();
    const daysSinceUpdate = Math.floor((now - modifiedMs) / (1000 * 60 * 60 * 24));
    return { ...source, daysSinceUpdate, stale: daysSinceUpdate > STALE_DAYS };
  });

  const staleCount = results.filter((r) => r.stale).length;

  return NextResponse.json({
    sources: results,
    staleCount,
    staleDays: STALE_DAYS,
    generatedAt: manifest.generatedAt,
  });
}
